server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/myweb?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.sisp.dao.entity
  mapperLocations: classpath:mapper/*.xml
  #开启Mybatis的二级缓存
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

